import type { BlockType } from '../../types'

/** Block types rendered as crossed planes (flowers/vegetation), not full cubes. */
export const CROSS_GEOMETRY_BLOCK_TYPES: BlockType[] = [
  'dead_bush',
  'cactus_flower',
  'dandelion',
  'poppy',
  'tulip_red',
  'tulip_orange',
  'tulip_white',
  'tulip_pink',
  'oxeye_daisy',
  'cornflower',
  'azure_bluet',
  'allium',
  'lily_of_the_valley',
  'blue_orchid',
  'fern',
  'large_fern',
  'brown_mushroom',
  'red_mushroom',
  'lily_pad',
  'sugar_cane',
  'kelp',
  'seagrass',
  'sea_pickle',
  'vine',
  'bamboo',
  'sweet_berry_bush',
  'pink_petals',
]
